//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterinaryСlinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Veterinary_Clinic : DbContext
    {
        public Veterinary_Clinic()
            : base("name=Veterinary_Clinic")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Medication> Medication { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Reception> Reception { get; set; }
        public virtual DbSet<ReceptionServices> ReceptionServices { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Treatment> Treatment { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Veterinarians> Veterinarians { get; set; }
        public virtual DbSet<View> View { get; set; }
    }
}
